alias monarch-save="git add . && git commit -m \"Update from Monarch CMD\" && git push"
alias monarch-save="git add . && git commit -m \"Update from Monarch CMD\" && git push"
alias monarch-save="git add . && git commit -m \"Update from Monarch CMD\" && git push"
alias monarch-save="git add . && git commit -m \"Update from Monarch CMD\" && git push"
alias monarch-save="git pull --rebase origin main && git add . && git commit -m \"Update from Monarch CMD\" && git push"
